### ISSUE TITLE
[BUG] When v0.2.0 installed from source on Chrome it fails to work

### ISSUE THREAD

**Issue by kdybicz** [secretescapes/aws-console-extension#6]
**Describe the bug**
After installing and setting up with accounts extension fails to work, when on AWS page:
```
Error handling response: TypeError: Cannot read property 'cloneNode' of null
    at addRole (chrome-extension://dblimoedomikibabccphkpmmffmgijje/content.js:44:31)
    at generate (chrome-extension://dblimoedomikibabccphkpmmffmgijje/content.js:156:4)
    at chrome-extension://dblimoedomikibabccphkpmmffmgijje/content.js:175:3
```

**To Reproduce**
Steps to reproduce the behaviour:
1. Install plugin from source
2. Upload AWS accounts JSON
3. Go to a AWS Console main page
4. See the above error in console

**Expected behavior**
Be able to see the dropdown with all uploaded accounts.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version: 0.0.2

**Additional context**
none

**Comment by icollar** [comment]
This is a known issue. I've taken a shortcut when creating the switch buttons on the mask panel. It reuses an existing role from the history tab so it can find the CSRF token, and also means we can skip manually constructing the switch form.

The work around here is to do a manual role switch, then reload and it should start working. What I should do is add some documentation and/or a popup warning that explains what needs to be done to get it working.

Easy to reproduce:
- enable extension in incognito/private
- login to the console and open the panel

![issue-6](https://user-images.githubusercontent.com/10746716/131532422-088d4495-d305-4bf4-b27b-b0f713733996.png)
